// leave off @2x/@3x
const images = {
  AbcNewsAu: require('../Images/abc-news-au.png'),
  ArsTechnica: require('../Images/ars-technica.png'),
  BusinessInsiderUk: require('../Images/business-insider-uk.png'),
  AlJazeeraEnglish: require('../Images/al-jazeera-english.png'),
  Buzzfeed: require('../Images/buzzfeed.png'),
  DailyMail: require('../Images/daily-mail.png'),
  Engadget: require('../Images/engadget.png'),
  Espn: require('../Images/espn.png'),
  FinancialTimes: require('../Images/financial-times.png'),
  BreitbartNews: require('../Images/breitbart-news.png'),
  EspnCricInfo: require('../Images/espn-cric-info.png'),
  FootballItalia: require('../Images/football-italia.png'),
  Fortune: require('../Images/fortune.png'),
  FourFourTwo: require('../Images/four-four-two.png'),
  FoxSports: require('../Images/fox-sports.png'),
  Ign: require('../Images/ign.png'),
  Mashable: require('../Images/mashable.png'),
  Metro: require('../Images/metro.png'),
  Mirror: require('../Images/mirror.png'),
  MtvNews: require('../Images/mtv-news.png'),
  Newsweek: require('../Images/newsweek.png'),
  NewYorkMagazine: require('../Images/new-york-magazine.png'),
  NflNews: require('../Images/nfl-news.png'),
  RedditRAll: require('../Images/reddit-r-all.png'),
  Reuters: require('../Images/reuters.png'),
  Talksport: require('../Images/talksport.png'),
  Techcrunch: require('../Images/techcrunch.png'),
  Techradar: require('../Images/techradar.png'),
  TheEconomist: require('../Images/the-economist.png'),
  TheGuardianUk: require('../Images/the-guardian-uk.png'),
  TheHindu: require('../Images/the-hindu.png'),
  TheLadBible: require('../Images/the-lad-bible.png'),
  TheSportBible: require('../Images/the-sport-bible.png'),
  TheTelegraph: require('../Images/the-telegraph.png'),
  TheTimesOfIndia: require('../Images/the-times-of-india.png'),
  TheVerge: require('../Images/the-verge.png'),
  Time: require('../Images/time.png'),
  UsaToday: require('../Images/usa-today.png')
}

export default images
